PointOfInterest:
  required:
    - id
  allOf:
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
  type: object
  description: |
    This entity contains a harmonised geographic description of a Point of Interest. This entity is used in applications
    that use spatial data and is applicable to Automotive, Environment, Industry and Smart City vertical segments and
    related IoT applications. This data model has been created in cooperation with the GSMA and the members of the
    IoT Big Data Project.
