PointOfInterest:
  required:
    - id
    - type
    - category
  allOf:
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
  type: object
  description: |
    This entity contains a harmonised geographic description of a Point of Interest. This entity is used in applications
    that use spatial data and is applicable to Automotive, Environment, Industry and Smart City vertical segments and
    related IoT applications. This data model has been created in cooperation with the GSMA and the members of the
    IoT Big Data Project.
  properties:
    address:
      "$ref": https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/address
    alternateName:
      x-ngsi:
        type: Property
        model: https://schema.org/Text
      type: string
      description: 'Alternative name for this point of interest.'
    areaServed:
      x-ngsi:
        type: Property
        model: https://schema.org/Text
      type: string
      description: ''
    category:
      x-ngsi:
        type: Property
      type: array
      description: |
        Category of this point of interest.
        
        Allowed values: Those defined by the [Factual taxonomy](https://github.com/Factual/places/blob/master/categories/factual_taxonomy.json)
        together with the extended categories described by the present
        specification (see below). For instance the value `113` corresponds to
        beaches, and the value `311` corresponds to museums.

        ## Extended POI Categories

        | Category | Description                |
        | :------- | :------------------------- |
        | `1478`   | `Public drinking fountain` |
        | `1479`   | `Public toilet`            |
        | `1480`   | `Registry office`          |

      items:
        type: string
    contactPoint:
      x-ngsi:
        type: Property
        model: https://schema.org/contactPoint
      type: object
      description: 'Contact point of this point of interest.'
    dataProvider:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/fiware-terms.yaml#/dataProvider
    description:
    description:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description
    location:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/location
    name:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/name
    owner:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/fiware-terms.yaml#/owner
    refSeeAlso:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/fiware-terms.yaml#/refSeeAlso
    source:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/fiware-terms.yaml#/source
