---
# Copyright (c) 2020 Contributors to Smart-Data-Models
# see https://github.com/smart-data-models/dataModel.Building

components:
  schemas:
    Store:
      $ref: 'https://smart-data-models.github.io/dataModel.PointOfInterest/Store/model.yaml#/Store'
info:
  description: |
    This entity Type models stores/shops in the city. The model is based on the one defined by Schema.org. In particular, the model contains a subset of the properties defined in the mentioned link, and a list of store categories, that can be afterwards specialized as concrete Types (see https://schema.org/Store).
  title: Store
  version: 1.0.0
openapi: 3.0.0
paths:
  /ngsi-ld/v1/entities:
    get:
      description: Retrieve a set of entities which matches a specific query from an NGSI-LD system
      parameters:
        - in: query
          name: type
          required: true
          schema:
            enum:
              - Store
            type: string
      responses:
        '200':
          content:
            application/ld+json:
              examples:
                keyvalues:
                  summary: Key-Values Pairs
                  value:
                    - $ref: 'https://smart-data-models.github.io/dataModel.PointOfInterest/Store/examples/example.json'
                normalized:
                  summary: Normalized NGSI-LD
                  value:
                    - $ref: 'https://smart-data-models.github.io/dataModel.PointOfInterest/Store/examples/example.jsonld'
          description: OK
      tags:
        - ngsi-ld
tags:
  - description: NGSI-LD Linked-data Format
    name: ngsi-ld
