Museum:
  required:
    - id
    - type
    - location
    - name
  allOf:
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
  type: object
  description: |
    This entity contains a harmonised geographic description of a museum. It is used in applications that use
    spatial data and is applicable to Tourism, Cultural, and Smart City vertical segments and related IoT applications.
    Special thanks to TURESPAÑA who provided some examples which inspired the development of this data model.

  properties:
    address:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/address
    alternateName:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/alternateName
    areaServed:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/areaServed
    artPeriod:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
    buildingType:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
        enum:
          - prehistoricPlace
          - acropolis
          - alcazaba
          - aqueduct
          - alcazar
          - amphitheatre
          - arch
          - polularArchitecture
          - basilica
          - road
          - chapel
          - cartuja
          - nobleHouse
          - residence
          - castle
          - castro
          - catacombs
          - cathedral
          - cloister
          - convent
          - prehistoricCave
          - dolmen
          - officeBuilding
          - houseBuilding
          - industrialBuilding
          - militaryBuilding
          - hermitage
          - fortress
          - sculpturalGroups
          - church
          - garden
          - fishMarket
          - masia
          - masiaFortificada
          - minaret
          - monastery
          - monolith
          - walls
          - necropolis
          - menhir
          - mansion
          - palace
          - pantheon
          - pazo
          - pyramid
          - bridge
          - gate
          - arcade
          - walledArea
          - sanctuary
          - grave
          - synagogue
          - taulasTalayotsNavetas
          - theathre
          - temple
          - spring
          - tower
          - archeologicalSite
          - university
          - graveyard
          - fortifiedTemple
          - civilEngineering
          - square
          - seminar
          - bullfightingRing
          - publicBuilding
          - town
          - cavesAndTouristicMines
          - proCathedral
          - mosque
          - circus
          - burialMound
        minItems: 1
        uniqueItems: true
    contactPoint:
      x-ngsi:
        type: Property
      type: object
      description: ''
    dataProvider:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    description:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description
    facilities:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
        enum:
          - elevator
          - cafeteria
          - shop
          - auditory
          - conferenceRoom
          - audioguide
          - cloakRoom
          - forDisabled
          - forBabies
          - guidedTour
          - restaurant
          - ramp
          - reservation
    featuredArtist:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        anyOf:
          - &ref_0
            anyOf:
              - type: string
                minLength: 1
                maxLength: 256
                pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
              - type: string
                format: uri
          - type: string
    historicalPeriod:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
    location:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/location
    museumType:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
        enum:
          - appliedArts
          - scienceAndTechnology
          - fineArts
          - music
          - history
          - sacredArt
          - archaeology
          - specials
          - decorativeArts
          - literature
          - medicineAndPharmacy
          - maritime
          - transports
          - military
          - wax
          - popularArtsAndTraditions
          - numismatic
          - unesco
          - ceramics
          - sumptuaryArts
          - naturalScience
          - prehistoric
          - ethnology
          - railway
          - mining
          - textile
          - sculpture
          - multiDisciplinar
          - painting
          - paleonthology
          - modernArt
          - thematic
          - architecture
          - museumHouse
          - cathedralMuseum
          - diocesanMuseum
          - universitary
          - contemporaryArt
          - bullfighting
    name:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/name
    openingHoursSpecification:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        properties:
          opens:
            type: string
            pattern: '[0-9]{2}:[0-9]{2}'
          closes:
            type: string
            pattern: '[0-9]{2}:[0-9]{2}'
          dayOfWeek:
            type: string
    owner:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/fiware-terms.yaml#/owner
    refSeeAlso:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/fiware-terms.yaml#/refSeeAlso
    source:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/fiware-terms.yaml#/source
    touristArea:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
