--- 
components: 
  schemas: 
    Beach: 
      $ref: "https://smart-data-models.github.io/dataModel.PointOfInterest/Beach/model.yaml#/Beach"
info: 
  description: |
    This entity contains a harmonised geographic description of a beach. It is used in applications that use
    spatial data and is applicable to Tourism, Environment, and Smart City vertical segments and related IoT
    applications. Special thanks to TURESPAÑA who provided some examples which inspired the development of this data model
  title: Beach
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - Beach
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.PointOfInterest/Beach/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.PointOfInterest/Beach/example-normalized-ld.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
